name: Build .deb packages on push

on:
  push:
  workflow_dispatch:

jobs:
  build-bookworm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -b -us -uc
          docker-image: debian:bookworm-slim
      - name: Rename
        run: |
          cd debian/artifacts
          for _f in mimic*.deb; do sudo mv "$_f" "Debian-12_$_f"; done
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bookworm
          path: debian/artifacts/*.deb
  build-noble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -b -us -uc
          docker-image: ubuntu:noble
      - name: Rename
        run: |
          cd debian/artifacts
          for _f in mimic*.deb; do sudo mv "$_f" "Ubuntu-24.04_$_f"; done
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: noble
          path: debian/artifacts/*.deb
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install python3 clang llvm bats bc ethtool iperf3 socat tshark wireguard-tools libjson-c-dev libffi-dev libelf-dev
      - name: Prepare libbpf
        run: |
          git clone --depth 1 --branch v1.4.0 https://github.com/libbpf/libbpf.git
          cd libbpf/src
          make
          sudo make install
      - name: Build
        run: make -j
      - name: Test
        run: sudo make test
