name: Release actions

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-deb:
    name: Build .deb packages for ${{ matrix.distro.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - name: Debian 12
            codename: bookworm
            image: debian:bookworm-slim
            extra-repos: |
              deb http://deb.debian.org/debian bookworm-backports main
            extra-cmd: |
              sed -i 's/clang/clang-16/' debian/control
              sed -i 's/BPF_CC=clang/BPF_CC=clang-16 COMPAT_LINUX_6_1=1/' debian/rules
          - name: Debian 13
            codename: trixie
            image: debian:trixie-slim
          # - name: Debian 14 (testing)
          #   codename: forky
          #   image: debian:forky-slim
          - name: Ubuntu 24.04
            codename: noble
            image: ubuntu:noble
            extra-repos: |
              deb http://archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse
            extra-cmd: |
              sed -i 's/clang,/clang, llvm,/' debian/control
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run pre-building script
        run: ${{ matrix.distro.extra-cmd }}
      - name: Build
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -b -us -uc
          docker-image: ${{ matrix.distro.image }}
          extra-repos: ${{ matrix.distro.extra-repos }}
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd debian/artifacts
          _files=($(find . -type f -name 'mimic*.deb' -printf '%P\n') $(find . -type f -name 'mimic*.ddeb' -printf '%P\n'))
          for _f in ${_files[@]}; do
            sudo mv "$_f" "${{ matrix.distro.codename }}_$_f";
            sha256sum "${{ matrix.distro.codename }}_$_f" > "../${{ matrix.distro.codename }}_$_f.sha256"
          done
          gh release upload $(sed 's|refs/tags/||' <(echo ${{ github.ref }})) ${_files[@]/#/${{ matrix.distro.codename }}_} ../*.sha256
