name: Release actions

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-deb:
    name: Build .deb packages for ${{ matrix.distro.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - name: Debian 12
            codename: bookworm
            image: debian:bookworm-slim
          - name: Ubuntu 24.04
            codename: noble
            image: ubuntu:noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -b -us -uc
          docker-image: ${{ matrix.distro.image }}
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd debian/artifacts
          for _f in mimic*.deb mimic*.ddeb; do
            sudo mv "$_f" "${{ matrix.distro.codename }}_$_f";
            sha256sum "${{ matrix.distro.codename }}_$_f" > "../${{ matrix.distro.codename }}_$_f.sha256"
          done
          gh release upload $(sed 's|refs/tags/||' <(echo ${{ github.ref }})) *.deb *.ddeb ../*.deb.sha256 ../*.ddeb.sha256
